// Generated by DB Solo 5.2.1 on 8 Nov, 2019 at 3:32:36 PM
package com.apepdcl.billdeskrecon.beans;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "NEWCONNECTION_REGISTER")
public class NewconnectionRegister implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		
	@Id
	private String ID;
	@Column
	private Date REGISTERED_ON;
	private Date CREATE_DATE;
	private Date UPDATE_DATE;
	private Date TOBEREC_DT;
	private Date PAYMENT_DT;
	private Date RELEASED_DT;
	private Date ESCALATION1_DT;
	private Date ESCALATION2_DT;
	private Date REISSUED_ON;
	private String REG_TYPE;
	private String REQUEST_TYPE;
	private String REGISTRATION_NUMBER;
	private String CUSTOMER_NAME;
	private String ADDRESS_1;
	private String ADDRESS_2;
	private String AREA_NAME;
	private String ADDRESS_4;
	private String PINCODE;
	private String PHONE;
	private String SOCIAL_GROUP;
	private String STATUS_ID;
	private String CATEGORY_ID;
	private String CONTRACT_LOAD;
	private String CREATED_BY;
	private String UPDATED_BY;
	private String RECORD_STATUS;
	private String OFFICE_ID;
	private String IS_DISPATCHED;
	private String CADDRESS_1;
	private String CADDRESS_2;
	private String CAREA_NAME;
	private String CADDRESS_4;
	private String SCNO;
	private String STATUS;
	private String LOCATION_TYPE;
	private String ADJACENT_SCNO;
	private String PR_NO;
	private String TOTAL_APPLICATION_FEE;
	private String REMARKS;
	private String TYPE;
	private String CONNECTED_LOAD;
	private String GROUPCODE;
	private String BCRC_NO;
	private String DIVISION_ID;
	private String PHASE;
	private String DEVELOPMENT_CHARGES;
	private String SECURITY_DEPOSIT;
	private String APPLICATION_FEE;
	private String REL_DISPATCH_STATUS;
	private String RE_ISSUE_STATUS;
	private String AREACODE;
	private String NEWCON_MASTERID;
	private String PURPOSE;
	private String METRIC;
	private String PAY_MODE;
	private String PROPOSED_LOAD;
	private String METER_REQUIRED;
	private String SL_CHARGES;
	private String MOBILE_NO;
	private String GFLAG;
	private String FATHER_HUSBAND_NAME;
	private String APARTMENT_ID;
	private String CENTER_CODE;
	private String SURNAME;
	private String PAN_NO;
	private String MTR_ID;
	private String GOVT_CODE;
	private String REGISTRATION_TYPE;
	private String BOOKED_BY_DPE;
	private String PROOFIDENTITY;
	private String APP_SUBMITTED_BY;
	private String EXIS_LOAD;
	private String APPLIED_CON_LOAD;
	private String ACTUAL_CON_LOAD;
	private String ACTUAL_CATEGORY;
	private String APPLIED_CATEGORY;
	private String MONTH;
	private String YEAR;
	private String DB_IP_ADDRESS;
	private String CONDITION;
	private String EMAIL;
	private String SUBDIV;
	private String CIRCLE;
	private String DOC_SUBMITED;
	private String SERVICE_TYPE;
	private String PR_NOEST;
	private String IS_LAYOUT;
	private String ADDITIONAL_SECURITY_DEPOSIT;
	private String AADHAR;
	private String SEC_CODE;
	private String BILLING_TYPE;
	private String DISPATCH_DATE;
	private String MTR_PHASE;
	private String CUSTOMER_HISTORY;
	private String AREA_CODE;
	private String FORM_ID;
	private String CC_NAME;
	private String CC_CODE;
	private String DATA_SOURCE;
	private String OLD_MTR_PHASE1;
	private String MESEVAREGNO;
	private String MEESEVAFLAG;
	private String MANDAL_NAME;
	private String WIRING_CERTIFICATE_TYPE;
	
	public String getID() {
		return ID;
	}
	public void setID(String iD) {
		ID = iD;
	}
	public Date getREGISTERED_ON() {
		return REGISTERED_ON;
	}
	public void setREGISTERED_ON(Date rEGISTERED_ON) {
		REGISTERED_ON = rEGISTERED_ON;
	}
	public Date getCREATE_DATE() {
		return CREATE_DATE;
	}
	public void setCREATE_DATE(Date cREATE_DATE) {
		CREATE_DATE = cREATE_DATE;
	}
	public Date getUPDATE_DATE() {
		return UPDATE_DATE;
	}
	public void setUPDATE_DATE(Date uPDATE_DATE) {
		UPDATE_DATE = uPDATE_DATE;
	}
	public Date getTOBEREC_DT() {
		return TOBEREC_DT;
	}
	public void setTOBEREC_DT(Date tOBEREC_DT) {
		TOBEREC_DT = tOBEREC_DT;
	}
	public Date getPAYMENT_DT() {
		return PAYMENT_DT;
	}
	public void setPAYMENT_DT(Date pAYMENT_DT) {
		PAYMENT_DT = pAYMENT_DT;
	}
	public Date getRELEASED_DT() {
		return RELEASED_DT;
	}
	public void setRELEASED_DT(Date rELEASED_DT) {
		RELEASED_DT = rELEASED_DT;
	}
	public Date getESCALATION1_DT() {
		return ESCALATION1_DT;
	}
	public void setESCALATION1_DT(Date eSCALATION1_DT) {
		ESCALATION1_DT = eSCALATION1_DT;
	}
	public Date getESCALATION2_DT() {
		return ESCALATION2_DT;
	}
	public void setESCALATION2_DT(Date eSCALATION2_DT) {
		ESCALATION2_DT = eSCALATION2_DT;
	}
	public Date getREISSUED_ON() {
		return REISSUED_ON;
	}
	public void setREISSUED_ON(Date rEISSUED_ON) {
		REISSUED_ON = rEISSUED_ON;
	}
	public String getREGISTRATION_NUMBER() {
		return REGISTRATION_NUMBER;
	}
	public void setREGISTRATION_NUMBER(String rEGISTRATION_NUMBER) {
		REGISTRATION_NUMBER = rEGISTRATION_NUMBER;
	}
	public String getCUSTOMER_NAME() {
		return CUSTOMER_NAME;
	}
	public void setCUSTOMER_NAME(String cUSTOMER_NAME) {
		CUSTOMER_NAME = cUSTOMER_NAME;
	}
	public String getADDRESS_1() {
		return ADDRESS_1;
	}
	public void setADDRESS_1(String aDDRESS_1) {
		ADDRESS_1 = aDDRESS_1;
	}
	public String getADDRESS_2() {
		return ADDRESS_2;
	}
	public void setADDRESS_2(String aDDRESS_2) {
		ADDRESS_2 = aDDRESS_2;
	}
	public String getAREA_NAME() {
		return AREA_NAME;
	}
	public void setAREA_NAME(String aREA_NAME) {
		AREA_NAME = aREA_NAME;
	}
	public String getADDRESS_4() {
		return ADDRESS_4;
	}
	public void setADDRESS_4(String aDDRESS_4) {
		ADDRESS_4 = aDDRESS_4;
	}
	public String getPINCODE() {
		return PINCODE;
	}
	public void setPINCODE(String pINCODE) {
		PINCODE = pINCODE;
	}
	public String getPHONE() {
		return PHONE;
	}
	public void setPHONE(String pHONE) {
		PHONE = pHONE;
	}
	public String getSOCIAL_GROUP() {
		return SOCIAL_GROUP;
	}
	public void setSOCIAL_GROUP(String sOCIAL_GROUP) {
		SOCIAL_GROUP = sOCIAL_GROUP;
	}
	public String getSTATUS_ID() {
		return STATUS_ID;
	}
	public void setSTATUS_ID(String sTATUS_ID) {
		STATUS_ID = sTATUS_ID;
	}
	public String getCATEGORY_ID() {
		return CATEGORY_ID;
	}
	public void setCATEGORY_ID(String cATEGORY_ID) {
		CATEGORY_ID = cATEGORY_ID;
	}
	public String getCONTRACT_LOAD() {
		return CONTRACT_LOAD;
	}
	public void setCONTRACT_LOAD(String cONTRACT_LOAD) {
		CONTRACT_LOAD = cONTRACT_LOAD;
	}
	public String getCREATED_BY() {
		return CREATED_BY;
	}
	public void setCREATED_BY(String cREATED_BY) {
		CREATED_BY = cREATED_BY;
	}
	public String getUPDATED_BY() {
		return UPDATED_BY;
	}
	public void setUPDATED_BY(String uPDATED_BY) {
		UPDATED_BY = uPDATED_BY;
	}
	public String getRECORD_STATUS() {
		return RECORD_STATUS;
	}
	public void setRECORD_STATUS(String rECORD_STATUS) {
		RECORD_STATUS = rECORD_STATUS;
	}
	public String getCADDRESS_1() {
		return CADDRESS_1;
	}
	public void setCADDRESS_1(String cADDRESS_1) {
		CADDRESS_1 = cADDRESS_1;
	}
	public String getCADDRESS_2() {
		return CADDRESS_2;
	}
	public void setCADDRESS_2(String cADDRESS_2) {
		CADDRESS_2 = cADDRESS_2;
	}
	public String getCAREA_NAME() {
		return CAREA_NAME;
	}
	public void setCAREA_NAME(String cAREA_NAME) {
		CAREA_NAME = cAREA_NAME;
	}
	public String getCADDRESS_4() {
		return CADDRESS_4;
	}
	public void setCADDRESS_4(String cADDRESS_4) {
		CADDRESS_4 = cADDRESS_4;
	}
	public String getSCNO() {
		return SCNO;
	}
	public void setSCNO(String sCNO) {
		SCNO = sCNO;
	}
	public String getSTATUS() {
		return STATUS;
	}
	public void setSTATUS(String sTATUS) {
		STATUS = sTATUS;
	}
	public String getADJACENT_SCNO() {
		return ADJACENT_SCNO;
	}
	public void setADJACENT_SCNO(String aDJACENT_SCNO) {
		ADJACENT_SCNO = aDJACENT_SCNO;
	}
	public String getPR_NO() {
		return PR_NO;
	}
	public void setPR_NO(String pR_NO) {
		PR_NO = pR_NO;
	}
	public String getTOTAL_APPLICATION_FEE() {
		return TOTAL_APPLICATION_FEE;
	}
	public void setTOTAL_APPLICATION_FEE(String tOTAL_APPLICATION_FEE) {
		TOTAL_APPLICATION_FEE = tOTAL_APPLICATION_FEE;
	}
	public String getREMARKS() {
		return REMARKS;
	}
	public void setREMARKS(String rEMARKS) {
		REMARKS = rEMARKS;
	}
	public String getTYPE() {
		return TYPE;
	}
	public void setTYPE(String tYPE) {
		TYPE = tYPE;
	}
	public String getCONNECTED_LOAD() {
		return CONNECTED_LOAD;
	}
	public void setCONNECTED_LOAD(String cONNECTED_LOAD) {
		CONNECTED_LOAD = cONNECTED_LOAD;
	}
	public String getGROUPCODE() {
		return GROUPCODE;
	}
	public void setGROUPCODE(String gROUPCODE) {
		GROUPCODE = gROUPCODE;
	}
	public String getBCRC_NO() {
		return BCRC_NO;
	}
	public void setBCRC_NO(String bCRC_NO) {
		BCRC_NO = bCRC_NO;
	}
	public String getDIVISION_ID() {
		return DIVISION_ID;
	}
	public void setDIVISION_ID(String dIVISION_ID) {
		DIVISION_ID = dIVISION_ID;
	}
	public String getPHASE() {
		return PHASE;
	}
	public void setPHASE(String pHASE) {
		PHASE = pHASE;
	}
	public String getDEVELOPMENT_CHARGES() {
		return DEVELOPMENT_CHARGES;
	}
	public void setDEVELOPMENT_CHARGES(String dEVELOPMENT_CHARGES) {
		DEVELOPMENT_CHARGES = dEVELOPMENT_CHARGES;
	}
	public String getSECURITY_DEPOSIT() {
		return SECURITY_DEPOSIT;
	}
	public void setSECURITY_DEPOSIT(String sECURITY_DEPOSIT) {
		SECURITY_DEPOSIT = sECURITY_DEPOSIT;
	}
	public String getAPPLICATION_FEE() {
		return APPLICATION_FEE;
	}
	public void setAPPLICATION_FEE(String aPPLICATION_FEE) {
		APPLICATION_FEE = aPPLICATION_FEE;
	}
	public String getAREACODE() {
		return AREACODE;
	}
	public void setAREACODE(String aREACODE) {
		AREACODE = aREACODE;
	}
	public String getNEWCON_MASTERID() {
		return NEWCON_MASTERID;
	}
	public void setNEWCON_MASTERID(String nEWCON_MASTERID) {
		NEWCON_MASTERID = nEWCON_MASTERID;
	}
	public String getPURPOSE() {
		return PURPOSE;
	}
	public void setPURPOSE(String pURPOSE) {
		PURPOSE = pURPOSE;
	}
	public String getPAY_MODE() {
		return PAY_MODE;
	}
	public void setPAY_MODE(String pAY_MODE) {
		PAY_MODE = pAY_MODE;
	}
	public String getPROPOSED_LOAD() {
		return PROPOSED_LOAD;
	}
	public void setPROPOSED_LOAD(String pROPOSED_LOAD) {
		PROPOSED_LOAD = pROPOSED_LOAD;
	}
	public String getSL_CHARGES() {
		return SL_CHARGES;
	}
	public void setSL_CHARGES(String sL_CHARGES) {
		SL_CHARGES = sL_CHARGES;
	}
	public String getMOBILE_NO() {
		return MOBILE_NO;
	}
	public void setMOBILE_NO(String mOBILE_NO) {
		MOBILE_NO = mOBILE_NO;
	}
	public String getGFLAG() {
		return GFLAG;
	}
	public void setGFLAG(String gFLAG) {
		GFLAG = gFLAG;
	}
	public String getAPARTMENT_ID() {
		return APARTMENT_ID;
	}
	public void setAPARTMENT_ID(String aPARTMENT_ID) {
		APARTMENT_ID = aPARTMENT_ID;
	}
	public String getSURNAME() {
		return SURNAME;
	}
	public void setSURNAME(String sURNAME) {
		SURNAME = sURNAME;
	}
	public String getMTR_ID() {
		return MTR_ID;
	}
	public void setMTR_ID(String mTR_ID) {
		MTR_ID = mTR_ID;
	}
	public String getGOVT_CODE() {
		return GOVT_CODE;
	}
	public void setGOVT_CODE(String gOVT_CODE) {
		GOVT_CODE = gOVT_CODE;
	}
	public String getREGISTRATION_TYPE() {
		return REGISTRATION_TYPE;
	}
	public void setREGISTRATION_TYPE(String rEGISTRATION_TYPE) {
		REGISTRATION_TYPE = rEGISTRATION_TYPE;
	}
	public String getBOOKED_BY_DPE() {
		return BOOKED_BY_DPE;
	}
	public void setBOOKED_BY_DPE(String bOOKED_BY_DPE) {
		BOOKED_BY_DPE = bOOKED_BY_DPE;
	}
	public String getPROOFIDENTITY() {
		return PROOFIDENTITY;
	}
	public void setPROOFIDENTITY(String pROOFIDENTITY) {
		PROOFIDENTITY = pROOFIDENTITY;
	}
	public String getAPPLIED_CON_LOAD() {
		return APPLIED_CON_LOAD;
	}
	public void setAPPLIED_CON_LOAD(String aPPLIED_CON_LOAD) {
		APPLIED_CON_LOAD = aPPLIED_CON_LOAD;
	}
	public String getACTUAL_CON_LOAD() {
		return ACTUAL_CON_LOAD;
	}
	public void setACTUAL_CON_LOAD(String aCTUAL_CON_LOAD) {
		ACTUAL_CON_LOAD = aCTUAL_CON_LOAD;
	}
	public String getACTUAL_CATEGORY() {
		return ACTUAL_CATEGORY;
	}
	public void setACTUAL_CATEGORY(String aCTUAL_CATEGORY) {
		ACTUAL_CATEGORY = aCTUAL_CATEGORY;
	}
	public String getAPPLIED_CATEGORY() {
		return APPLIED_CATEGORY;
	}
	public void setAPPLIED_CATEGORY(String aPPLIED_CATEGORY) {
		APPLIED_CATEGORY = aPPLIED_CATEGORY;
	}
	public String getYEAR() {
		return YEAR;
	}
	public void setYEAR(String yEAR) {
		YEAR = yEAR;
	}
	public String getDB_IP_ADDRESS() {
		return DB_IP_ADDRESS;
	}
	public void setDB_IP_ADDRESS(String dB_IP_ADDRESS) {
		DB_IP_ADDRESS = dB_IP_ADDRESS;
	}
	public String getCONDITION() {
		return CONDITION;
	}
	public void setCONDITION(String cONDITION) {
		CONDITION = cONDITION;
	}
	public String getEMAIL() {
		return EMAIL;
	}
	public void setEMAIL(String eMAIL) {
		EMAIL = eMAIL;
	}
	public String getCIRCLE() {
		return CIRCLE;
	}
	public void setCIRCLE(String cIRCLE) {
		CIRCLE = cIRCLE;
	}
	public String getDOC_SUBMITED() {
		return DOC_SUBMITED;
	}
	public void setDOC_SUBMITED(String dOC_SUBMITED) {
		DOC_SUBMITED = dOC_SUBMITED;
	}
	public String getSERVICE_TYPE() {
		return SERVICE_TYPE;
	}
	public void setSERVICE_TYPE(String sERVICE_TYPE) {
		SERVICE_TYPE = sERVICE_TYPE;
	}
	public String getPR_NOEST() {
		return PR_NOEST;
	}
	public void setPR_NOEST(String pR_NOEST) {
		PR_NOEST = pR_NOEST;
	}
	public String getIS_LAYOUT() {
		return IS_LAYOUT;
	}
	public void setIS_LAYOUT(String iS_LAYOUT) {
		IS_LAYOUT = iS_LAYOUT;
	}
	public String getREG_TYPE() {
		return REG_TYPE;
	}
	public void setREG_TYPE(String rEG_TYPE) {
		REG_TYPE = rEG_TYPE;
	}
	public String getADDITIONAL_SECURITY_DEPOSIT() {
		return ADDITIONAL_SECURITY_DEPOSIT;
	}
	public void setADDITIONAL_SECURITY_DEPOSIT(String aDDITIONAL_SECURITY_DEPOSIT) {
		ADDITIONAL_SECURITY_DEPOSIT = aDDITIONAL_SECURITY_DEPOSIT;
	}
	public String getAADHAR() {
		return AADHAR;
	}
	public void setAADHAR(String aADHAR) {
		AADHAR = aADHAR;
	}
	public String getSEC_CODE() {
		return SEC_CODE;
	}
	public void setSEC_CODE(String sEC_CODE) {
		SEC_CODE = sEC_CODE;
	}
	public String getBILLING_TYPE() {
		return BILLING_TYPE;
	}
	public void setBILLING_TYPE(String bILLING_TYPE) {
		BILLING_TYPE = bILLING_TYPE;
	}
	public String getDISPATCH_DATE() {
		return DISPATCH_DATE;
	}
	public void setDISPATCH_DATE(String dISPATCH_DATE) {
		DISPATCH_DATE = dISPATCH_DATE;
	}
	public String getMTR_PHASE() {
		return MTR_PHASE;
	}
	public void setMTR_PHASE(String mTR_PHASE) {
		MTR_PHASE = mTR_PHASE;
	}
	public String getCUSTOMER_HISTORY() {
		return CUSTOMER_HISTORY;
	}
	public void setCUSTOMER_HISTORY(String cUSTOMER_HISTORY) {
		CUSTOMER_HISTORY = cUSTOMER_HISTORY;
	}
	public String getDATA_SOURCE() {
		return DATA_SOURCE;
	}
	public void setDATA_SOURCE(String dATA_SOURCE) {
		DATA_SOURCE = dATA_SOURCE;
	}
	public String getFORM_ID() {
		return FORM_ID;
	}
	public void setFORM_ID(String fORM_ID) {
		FORM_ID = fORM_ID;
	}
	public String getMEESEVAFLAG() {
		return MEESEVAFLAG;
	}
	public void setMEESEVAFLAG(String mEESEVAFLAG) {
		MEESEVAFLAG = mEESEVAFLAG;
	}
	public String getMESEVAREGNO() {
		return MESEVAREGNO;
	}
	public void setMESEVAREGNO(String mESEVAREGNO) {
		MESEVAREGNO = mESEVAREGNO;
	}
	public String getMANDAL_NAME() {
		return MANDAL_NAME;
	}
	public void setMANDAL_NAME(String mANDAL_NAME) {
		MANDAL_NAME = mANDAL_NAME;
	}
	public String getWIRING_CERTIFICATE_TYPE() {
		return WIRING_CERTIFICATE_TYPE;
	}
	public void setWIRING_CERTIFICATE_TYPE(String wIRING_CERTIFICATE_TYPE) {
		WIRING_CERTIFICATE_TYPE = wIRING_CERTIFICATE_TYPE;
	}
	public String getAREA_CODE() {
		return AREA_CODE;
	}
	public void setAREA_CODE(String aREA_CODE) {
		AREA_CODE = aREA_CODE;
	}
	public String getOFFICE_ID() {
		return OFFICE_ID;
	}
	public void setOFFICE_ID(String oFFICE_ID) {
		OFFICE_ID = oFFICE_ID;
	}
	public String getCENTER_CODE() {
		return CENTER_CODE;
	}
	public void setCENTER_CODE(String cENTER_CODE) {
		CENTER_CODE = cENTER_CODE;
	}
	public String getLOCATION_TYPE() {
		return LOCATION_TYPE;
	}
	public void setLOCATION_TYPE(String lOCATION_TYPE) {
		LOCATION_TYPE = lOCATION_TYPE;
	}
	public String getAPP_SUBMITTED_BY() {
		return APP_SUBMITTED_BY;
	}
	public void setAPP_SUBMITTED_BY(String aPP_SUBMITTED_BY) {
		APP_SUBMITTED_BY = aPP_SUBMITTED_BY;
	}
	public String getCC_NAME() {
		return CC_NAME;
	}
	public void setCC_NAME(String cC_NAME) {
		CC_NAME = cC_NAME;
	}
	public String getCC_CODE() {
		return CC_CODE;
	}
	public void setCC_CODE(String cC_CODE) {
		CC_CODE = cC_CODE;
	}
	public String getIS_DISPATCHED() {
		return IS_DISPATCHED;
	}
	public void setIS_DISPATCHED(String iS_DISPATCHED) {
		IS_DISPATCHED = iS_DISPATCHED;
	}
	public String getMETRIC() {
		return METRIC;
	}
	public void setMETRIC(String mETRIC) {
		METRIC = mETRIC;
	}
	public String getMETER_REQUIRED() {
		return METER_REQUIRED;
	}
	public void setMETER_REQUIRED(String mETER_REQUIRED) {
		METER_REQUIRED = mETER_REQUIRED;
	}
	public String getFATHER_HUSBAND_NAME() {
		return FATHER_HUSBAND_NAME;
	}
	public void setFATHER_HUSBAND_NAME(String fATHER_HUSBAND_NAME) {
		FATHER_HUSBAND_NAME = fATHER_HUSBAND_NAME;
	}
	public String getMONTH() {
		return MONTH;
	}
	public void setMONTH(String mONTH) {
		MONTH = mONTH;
	}
	public String getPAN_NO() {
		return PAN_NO;
	}
	public void setPAN_NO(String pAN_NO) {
		PAN_NO = pAN_NO;
	}
	public String getEXIS_LOAD() {
		return EXIS_LOAD;
	}
	public void setEXIS_LOAD(String eXIS_LOAD) {
		EXIS_LOAD = eXIS_LOAD;
	}
	public String getSUBDIV() {
		return SUBDIV;
	}
	public void setSUBDIV(String sUBDIV) {
		SUBDIV = sUBDIV;
	}
	public String getREL_DISPATCH_STATUS() {
		return REL_DISPATCH_STATUS;
	}
	public void setREL_DISPATCH_STATUS(String rEL_DISPATCH_STATUS) {
		REL_DISPATCH_STATUS = rEL_DISPATCH_STATUS;
	}
	public String getRE_ISSUE_STATUS() {
		return RE_ISSUE_STATUS;
	}
	public void setRE_ISSUE_STATUS(String rE_ISSUE_STATUS) {
		RE_ISSUE_STATUS = rE_ISSUE_STATUS;
	}
	public String getREQUEST_TYPE() {
		return REQUEST_TYPE;
	}
	public void setREQUEST_TYPE(String rEQUEST_TYPE) {
		REQUEST_TYPE = rEQUEST_TYPE;
	}
	public String getOLD_MTR_PHASE1() {
		return OLD_MTR_PHASE1;
	}
	public void setOLD_MTR_PHASE1(String oLD_MTR_PHASE1) {
		OLD_MTR_PHASE1 = oLD_MTR_PHASE1;
	}
	
//	private Date SL_CHARGES_DT;
//	private Date REJECTED_ON;
//	private Date ACTUAL_REL_DATE;
//	private Date ACTUAL_REJ_DATE;
//	private Date SD_PAYMENT_DT;
//	private Date SD_INTIMATION_DT;
//	private Date ESC_DISPATCH_DT;
//	private Date PAYMENT_PAID_DT;
//	private Date PAYMENT_INT_DT;
//	private Date TOBEPAYMENT_INT_DT;
//	private Date PR_DATE;
//	private Date ONLINE_RE_SUBMIT_DT;
//	private Date ADVCC_CHG_PRDT;
//	private Date EPIMRS_UPLD_DT;
//	private Date ELELAYCHG_PRDT;
//	private Date INTIMATION_DATE;
//	private Date INSPECTION_ON;
//	private Date DELCS_NOTICE_DT;
//	private Date DELCALLCENTER_DT;
//	private Date DEL_ACT_DT;
//	private Date COPY_RECV_DT;
//	private Date HARD_COPY_DT;
//	private Date CHK_HCC_DT;
//	private Date MTR_ISSUE_DT;
//	private Date SOP_TOBEREL_DT;
//	private Date EMERGENCY_CHG_PRDT;
//	private String IS_APP_FEES_REQUIRED;
//	private String REASON_MODIFY;
//	private String DD_AMOUNT;
//	private String REASON_FOR_REJECTION;
//	private String POLE_NUMBER;
//	private String PCB_NO;
//	private String REASON_FOR_PENDING;
//	private String TRANSFORMER_NUMBER;
//	private String DD_NUMBER;
//	private String BANK_NAME;
//	private String DISPATCH_LETTER_NO;
//	private String PAYMENT_DETAILS;
//	private String CHECK_CONDITION;
//	private String PREV_OFFICE_ID;
//	private String FIRST_BILL_NO;
//	private String FIRST_BILL_AMT;
//	private String CAPACITY;
//	private String PERSON_REL_DESIG;
//	private String METERMAKE;
//	private String TC_CEAL2;
//	private String PERSON_REL;
//	private String TC_CEAL1;
//	private String SERIALNO;
//	private String INITIAL_READING;
//	private String TR_REF_NO;
//	private String WO_ID;
//	private String SLC_PRNO;
//	private String DEV_PRNO;
//	private String SD_PRNO;
//	private String TYPE_OF_HT;
//	private String TYPE_OF_CAT;
//	private String TEL_FED_BY;
//	private String TEL_FED_DETAILS;
//	private String TEL_FED_CONF;
//	private String RECEIVER;
//	private String DEVPCB_NO;
//	private String LTAPCB;
//	private String SDPCB;
//	private String ACD_REQUIREMENT;
//	private String NO_OF_HOLIDAYS;
//	private String FEEDER_CODE;
//	private String DTR_CODE;
//	private String SC_WO_NO;
//	private String LINE_TYPE;
//	private String ESCALATION_STATUS;
//	private String PROPOSED_PHASE;
//	private String CHANGE_DETAILS;
//	private String ANYREMARKS;
//	private String COMP_REP;
//	private String EXISTING_SCNO;
//	private String COMP_REP_DESIG;
//	private String LIGHTING_LOAD;
//	private String GPA_REGNO;
//	private String ED_APPLICABLE;
//	private String ALTERNATE_SCNO;
//	private String TOKEN_NO;
//	private String SLC_REMARKS;
//	private String SD_REMARKS;
//	private String EST_REMARKS;
//	private String EPIMRS_EST_NO;
//	private String EREF_ID;
//	private String OFFICE_PHONE;
//	private String CONS_SATISFICATION;
//	private String SC_CHG;
//	private String SC_CHG_PRNO;
//	private String EMERGENCY_CHG;
//	private String EMERGENCY_CHG_PRNO;
//	private String ADVCC_CHG;
//	private String ADVCC_CHG_PRNO;
//	private String ELELAYCHG_PRNO;
//	private String ELE_LAYCHG;
//	private String GATEPASS_NO;
//	private String BEDROOM_TYPE;
//	private String CORRECT_SECTION;
//	private String SUB_GROUP;
//	private String SEASONAL;
//	private String KVAH;
//	private String LI_TYPE;
//	private String REBATE;
//	private String KVARH;
//	private String CAPACITOR;
//	private String DWELLINGS;
//	private String EXIS_PHASE;
//	private String EST_NUM;
//	private String DISPATCH_NO;
//	private String SANC_AUTH;
//	private String EST_SANCNO;
//	private String ADDR_TO;
//	private String IS_INTIMATED;
//	private String IS_ESTIMATE_REQUIRED;
//	private String INSPECTION_DT;
//	private String SUPPLY_POINT;
//	private String IS_REC;
//	private String IS_LOAD_REQUIRED;
//	private String STRUCTURE_CODE;
//	private String IS_LESS_CREDIT;
//	private String REQUEST_NUMBER;
//	private String POWER_DTR_CAP;
//	private String APSHCL;
//	private String GPS;
//	private String FEEDERNAME_NUMBER;
//	private String REQUISITION_NO;
//	private String REQUISITION_DT;
//	private String IMAGE;
//	private String SIGN;
//	private String SO_DO;
//	private String UDC_SCNO;
//	private String UDC_ARREARS;
//	private String ERO_NAME;
//	private String PREMISES;
//	private String TESTREP_SENTON;
//	private String DISPATCHNO;
//	private String EST_REPORT;
//	private String TOTALCOST;
//	private String LOAD_INV;
//	private String MEESEVA_DOC_FLAG;
//	private String DTR_INV;
//	private String FIRM_NAME;
//	private String LINE_INV;
//	private String SHOULD_CONSUMER_PAY;
//	private String BILLINGMODE;
//	private String REQUEST_REFNO;
//	private String EST_DATE;
//	private String EST_SOURCE;
//	private String EST_FROM;
//	private String WO_NUM;
//	private String ENTER_WO;
//	private String IS_LOAD_APPROVED;
//	private String APPROVED_AUTH;
//	private String SAP_WONUM;
//	private String ADDRESS;
//	private String LOAD_APPROVAL_NO;
//	private String LOAD_APPROVAL_DT;
//	private String INSPECT_APPROVED_AUTH;
//	private String IS_ESTIMATE_PREPARED;
//	private String RELCONDITION;
//	private String KWH;
//	private String CT_RATIO;
//	private String CUSTOMER_BANK;
//	private String ACCOUNT_NO;
//	private String GATEPASSNO;
//	private String REMARKS_DISP;
//	private String GRP_ADDRESS;
//	private String PORTED;
//	private String MTR_LOCATION;
//	private String MTR_HEIGHT;
//	private String MRT_CEAL2;
//	private String MRT_CEAL1;
//	private String WO_NO;
//	private String CAPACITOR_MAKE;
//	private String CHECDOCF;
//	private String JDRIVINGFILL;
//	private String MTR_NUMBER;
//	private String MTR_CAPACITY;
//	private String MTR_TYPE;
//	private String JAADHARCARDFILL;
//	private String APPARTMENT_NAME;
//	private String JRATIONFILL;
//	private String CAPACITOR_SLNO;
//	private String MTR_SEALNO2;
//	private String JBLURF;
//	private String TOTAMT;
//	private String BAL_TOT;
//	private String MTR_MAKE;
//	private String MTR_CONSTANT;
//	private String MTR_DEGIT;
//	private String OCOPIES;
//	private String MTR_SEALNO1;
//	private String METERNOPHASE;
//	private String TC_SEALNO2;
//	private String TC_SEALNO1;
//	private String MTR_NUMBER_CALLAUTO;
//	private String MF_KWH;
//	private String MF_KVAH;
//	private String REJREASON;
//	private String JED_APPLICABLE;
//	private String FIELD45;
//	private String CADDRESS_3;
//	private String SUBCAT_ID;
//	private String MTR_ISSUED_BY;
//	private String FEEDER_CODENN;
//	private String TEMPID;
//	private String OLD_MTR_NUMBER;
//	private String TVRMETER;
//	private String ISSUEDATEEE;
//	private String OLD_MTR_CONSTANT1;
//	private String OLD_KVARH1;
//	private String OLD_KVAH1;
//	private String OLD_MTR_DEGIT1;
//	private String OLD_MTR_SEALNO3;
//	private String OLD_TC_CEAL3;
//	private String KWH1;
//	private String OLD_MTR_TYPEA;
//	private String OLD_CT_RATIO;
//	private String OLD_MTR_CONSTANTA;
//	private String OLD_MTR_SEALNO1A;
//	private String OLD_KWHA;
//	private String OLD_MTR_SEALNO2A;
//	private String OLD_KVAHA;
//	private String OLD_MTR_DEGITA;
//	private String OLD_CT_RATIOA;
//	private String OLD_KVARHA;
//	private String DELCS_REASON;
//	private String DELCS_REMARKS;
//	private String DELCS_REFNUM;
//	private String MTRID;
//	private String REPLACEMENT_REASON;
//	private String CONTRACTED_LOAD;
//	private String EPIMRS_STATUS;
//	private String STATUS_FLAG;
//	private String CONTRACT_LOAD1;
//	private String PROPOSED_LOAD1;
//	private String REJ_MESAVA;
//	private String CONNECTED_LOAD1;
//	private String NO_OF_DAYS;
//	private String THUMB;
//	private String USERID;
//	private String SCSP_TSP;
//	private String APT_HEIGHT;
//	private String NEWMTR;
//	private String REMARKS_SEC;
//	private String PHASE_OLD;
//	private String CHECK_FD;
//	private String NEWCON48_ID;
//	private String OLD_MTR_TYPEB;
//	private String ACKNOWLEDGE;
//	private String LOAD_PENDINGAT;
//	private String IS_GIS;
//	private String MF_KVA;
//	private String FEASIBILITY;
//	private String MONTHLY;
//	private String MTR_NUMBERR;
//	private String MTR_NUMBERM;
//	private String MODULE_ID;
//	private String SCNOFULL;
//	private String SCNOFULL1;
//	private String SEC_ISS_DATE;
//	private String IS_LIVE;
//	private String CAPACITY_KVARH;
//	private String OLD_MTR_NUMBERA;
//	private String TRI_VECTOR;
//	private String CONS_NUMBER;
//	private String OLD_MTR_CAPACITYA;
//	private String CONVERSION_TYPEIII;
//	private String IS_LIVECHECK;
//	private String OLD_MTR_MAKEA;
//	private String CONVERSION_TYPEI;
//	private String OLD_MF;
//	private String TOBE_ESTPREP_DT;
//	private String SOLAR_PUMP;
//	private String SOLAR_PUMP2;
//	private String HT_SERVICENO;
//	private String CUSTOMER_HISTORY1;
//	private String CUSTOMER_HISTORY2;
//	private String PROOFDOCS;
//	private String IDENTITYDOCS;
//	private String DOCUMENTDOCS;
//	private String PROFATTCDOCS;
//	private String REGISTRATION_NO;
//	private String NONM;
//	private String ONLINE_RE_SUBMIT;
//	private String COMPLAINT_NO;
//	private String CHANGE_MADE;
//	private String SDSDS;
//	private String SDDATE;
//	private String CUSTOMER_NAME_OLD;
//	private String SURNAME_OLD;
//	private String SOLAR_PUMP_OLD;
//	private String PROPOSED_LOAD_OLD;
//	private String CONTRACT_LOAD_OLD;
//	private String PHASE_OLD1;
//	private String OFFICE_ID_OLD;
//	private String APARTMENT_ID_OLD;
//	private String HH_TYPE;
//	private String CPACITY_KVARH;
//	private String REJECTED_REASON_DR;
//	private String POLE_NUMBERB;
//	private String RES;
//	private String MF_KVAM;
//	private String MF_KVAX;
//	private String PATICULARSVISABLE;
//	private String JALASIRI;
//	private String MTRHEIGHT;
//	private String POLENO;
//	private String STRUCTCODE;
//	private String TCSEAL;
//	private String METER_LOACTION;
//	private String FIELD100;
//	private String CONFIRMED_BY;
//	private String ASD_AMONT;
//	private String BALSD_AMOUNT;
//	private String BALDC_AMOUNT;
//	private String BALASD_AMOUNT;
//	private String BALAPP_FEE;
//	private String BCRC_UPDATE_DT;
//	private String IS_APDRP;
//	private String MTR_SIDE;
	

	}
